[project]
name = "pydata-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=4.0.1",
    "pylint>=3.3.2",
    "pytest>=8.3.4",
]
